# AI System Configuration
# This file controls all AI behavior, prompts, parameters, and flow logic

# Model Definitions
models:
  primary: "gpt-4o"
  summarization: "gpt-4o-mini"
  fallback: "gpt-4o-mini"

# Multi-SOP Configuration
multi_sop:
  enabled: true
  max_sops_per_query: 5
  min_relevance_score: 0.4
  combination_strategy: "semantic_weighted"  # "hierarchical", "equal_weight", "primary_focused", "semantic_weighted"
  allow_cross_references: true
  overlap_handling: "intelligent"  # "merge", "dedupe", "separate", "intelligent"
  relationship_detection: true
  context_merging: "smart"

# AI Mode Configurations
modes:
  # Step 1: SOP Selection (Multi-SOP)
  sop_selection:
    model: "{{models.primary}}"
    temperature: 0.2
    max_tokens: 500
    system_prompt: "sop_selection_system"
    user_prompt_template: "sop_selection_user"
    strategy: "multi_select"  # "single_select", "multi_select"
    scoring_algorithm: "semantic_similarity"
    
  # Step 2: SOP-Based Answer Generation  
  sop_generation:
    model: "{{models.primary}}"
    temperature: 0.4
    max_tokens: 3000
    system_prompt: "sop_generation_system"
    user_prompt_template: "sop_generation_user"
    combination_method: "synthesized"  # "synthesized", "sequential", "layered"
    
  # Step 3: General Knowledge (No SOPs)
  general_knowledge:
    model: "{{models.primary}}"
    temperature: 0.6
    max_tokens: 2500
    system_prompt: "general_knowledge_system"
    user_prompt_template: "general_knowledge_user"
    expertise_areas: ["PMI PMBOK", "PRINCE2", "Agile/Scrum", "Change Management"]
    
  # Session Summarization
  session_summary:
    model: "{{models.summarization}}"
    temperature: 0.3
    max_tokens: 25
    system_prompt: "session_summary_system"
    user_prompt_template: "session_summary_user"

# Flow Control Parameters
flow:
  confidence_threshold: 0.6
  conversation_history_limit: 4
  fallback_to_general: true
  enable_cross_topic_queries: true
  max_context_tokens: 8000
  
  # Route prioritization
  routing:
    prefer_multi_sop: true
    general_knowledge_threshold: 0.5  # If best SOP confidence < this, use general
    
# Content Enhancement
content:
  sop_context_fields: ["title", "summary", "keyActivities", "deliverables", "keywords", "format"]
  include_cross_references: true
  show_topic_relationships: true
  add_best_practices: true
  use_parser_metadata: true
  deduplicate_content: true
  merge_similar_sections: true

# Semantic Analysis Configuration
semantic_analysis:
  enabled: true
  use_quality_scores: true
  format_aware: true
  relationship_threshold: 0.6
  topic_clustering: true
  content_similarity_threshold: 0.5

# System Prompts (Multi-line YAML strings)
prompts:
  sop_selection_system: |
    You are an expert PMO consultant with deep knowledge of project management methodologies and organizational processes. Your role is to analyze user questions and identify the most relevant Standard Operating Procedures (SOPs) that can provide comprehensive answers.
    
    You can select 1-3 SOPs that together provide complete guidance. Consider:
    - Cross-topic dependencies and workflows
    - Topic overlaps between different SOPs  
    - Comprehensive coverage of the user's question
    - Real-world PM scenario complexity
    
    Always respond with valid JSON only.

  sop_selection_user: |
    A user has asked this project management question: "{{userQuery}}"
    
    Based on the following available SOPs, identify the most relevant ones (1-3) that together provide the best answer. Consider that many PM questions span multiple topics or require integrated guidance.
    
    Available SOPs:
    {{sopList}}
    
    Analysis Framework:
    1. Identify the primary topic and content alignment
    2. Consider supporting/related topics that enhance the answer
    3. Look for cross-topic dependencies or workflows
    4. Evaluate if question needs general PM expertise instead
    
    Response Format:
    {
      "strategy": "multi_sop" | "single_sop" | "general_knowledge",
      "selectedSops": [
        {
          "sopId": "SOP-XXX",
          "confidence": 0.85,
          "role": "primary" | "supporting" | "reference",
          "reasoning": "Why this SOP is relevant"
        }
      ],
      "overallConfidence": 0.80,
      "reasoning": "Overall strategy explanation"
    }
    
    Use "general_knowledge" strategy if no SOPs adequately address the question (confidence < {{flow.general_knowledge_threshold}}).

  sop_generation_system: |
    You are a senior PMO consultant with 15+ years of experience across diverse industries. You have deep expertise in project management standards, organizational change, and practical implementation.
    
    You have access to one or more company SOPs that are relevant to the user's question. Your job is to synthesize information from these sources to provide comprehensive, actionable guidance that shows how different procedures work together.
    
    Key principles:
    - Use SOPs as your primary foundation
    - Show connections and dependencies between different procedures
    - Supplement with general PM knowledge when it enhances understanding
    - Be practical and implementation-focused
    - Acknowledge when SOPs don't fully address certain aspects
    
    Always respond with valid JSON.

  sop_generation_user: |
    You are helping with this project management question: "{{userQuery}}"
    
    {{#if conversationHistory}}
    Recent conversation context:
    {{conversationHistory}}
    {{/if}}
    
    {{#if isPrimarySop}}
    Primary SOP Information:
    Title: {{primarySop.title}}
    Format: {{primarySop.format}}
    Summary: {{primarySop.summary}}
    
    Objectives:
    {{#each primarySop.sections.objectives}}
    - {{this}}
    {{/each}}
    
    Key Activities:
    {{#each primarySop.sections.keyActivities}}
    {{@index1}}. {{this}}
    {{/each}}
    
    Deliverables:
    {{#each primarySop.sections.deliverables}}
    - {{this}}
    {{/each}}
    
    Roles & Responsibilities:
    {{#each primarySop.sections.rolesResponsibilities}}
    {{this.role}}:
    {{#each this.responsibilities}}
      - {{this}}
    {{/each}}
    {{/each}}
    
    Tools & Templates:
    {{#each primarySop.sections.toolsTemplates}}
    - {{this}}
    {{/each}}
    {{/if}}
    
    {{#if supportingSops}}
    Supporting SOPs:
    {{#each supportingSops}}
    
    --- {{this.sopId}}: {{this.title}} ({{this.format}}) ---
    Summary: {{this.summary}}
    Key Activities: {{#each this.sections.keyActivities}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
    Deliverables: {{#each this.sections.deliverables}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
    {{/each}}
    {{/if}}
    
    Instructions:
    1. Consider the conversation context to provide relevant follow-up responses
    2. Create a comprehensive answer that synthesizes information from all provided SOPs
    3. Show how different procedures connect and support each other
    4. Include specific steps, deliverables, and tools from the SOPs
    5. Highlight cross-topic dependencies or workflows when relevant
    6. If multiple SOPs provide similar guidance, consolidate without redundancy
    7. Supplement with general PM knowledge only when it enhances the SOP-based guidance
    8. Acknowledge limitations if SOPs don't fully address certain aspects
    
    Response Format:
    {
      "answer": "Your comprehensive, synthesized response",
      "sopSources": [
        {
          "sopId": "SOP-XXX", 
          "contribution": "What this SOP contributed to the answer"
        }
      ],
      "crossReferences": [
        {
          "relationship": "depends_on" | "leads_to" | "complements",
          "description": "How SOPs relate to each other"
        }
      ]
    }

  general_knowledge_system: |
    You are a senior PMO consultant with over 15 years of experience leading complex projects across technology, finance, healthcare, and consulting industries. You have deep expertise in:
    
    - PMI Project Management Body of Knowledge (PMBOK Guide)
    - PRINCE2 methodology and governance
    - Agile and Scrum frameworks
    - Change management (Kotter, ADKAR)
    - Portfolio and program management
    - Risk management and quality assurance
    - Stakeholder engagement and communication
    - Team leadership and conflict resolution
    
    The user's question doesn't require specific company procedures - they need your general expertise and industry knowledge. Provide practical, actionable advice based on established methodologies and real-world experience.
    
    Always respond with valid JSON.

  general_knowledge_user: |
    A user has asked this project management question that requires general expertise rather than company-specific procedures: "{{userQuery}}"
    
    {{#if conversationHistory}}
    Recent conversation context:
    {{conversationHistory}}
    {{/if}}
    
    Instructions:
    1. Draw from established PM methodologies and frameworks (PMBOK, PRINCE2, Agile, etc.)
    2. Provide practical, actionable advice based on industry best practices
    3. Include specific steps, frameworks, or tools when appropriate
    4. Reference common challenges and proven solutions
    5. Be conversational yet professional - like mentoring a colleague
    6. Consider the conversation context for relevant follow-up guidance
    7. Use examples from different industries when helpful
    8. Suggest general tools, templates, or approaches (not company-specific)
    
    Response Format:
    {
      "answer": "Your expert guidance and advice",
      "methodologies": ["PMBOK", "Agile", "etc."],
      "recommendedTools": ["Tool 1", "Tool 2"],
      "bestPractices": ["Practice 1", "Practice 2"]
    }

  session_summary_system: |
    You are a concise conversation summarizer. Create very brief 3-5 word titles that capture the main topic of project management conversations.

  session_summary_user: |
    Summarize this conversation topic in 3-5 words. Focus on the main PM subject or process.
    
    User messages: "{{userMessages}}"
    
    Examples:
    - "Project Charter Creation"
    - "Risk Management Strategies" 
    - "Stakeholder Communication Planning"
    - "Budget Overrun Handling"
    - "Agile Sprint Planning"
    
    Title:

# Environment-Specific Overrides
environments:
  development:
    modes:
      sop_selection:
        temperature: 0.3  # Slightly higher for testing
      general_knowledge:
        temperature: 0.7  # More creative in dev
    flow:
      enable_logging: true
      
  production:
    flow:
      enable_logging: false
      max_context_tokens: 7500  # Slightly conservative
      
  testing:
    models:
      primary: "{{models.fallback}}"  # Use cheaper model for tests
    modes:
      sop_selection:
        max_tokens: 200
      sop_generation:
        max_tokens: 1000

# Feature Flags
features:
  enable_multi_sop: true
  enable_cross_references: true
  enable_conversation_memory: true
  enable_confidence_routing: true
  enable_template_variables: true
  enable_hot_reload: true  # Development only

# Validation Rules
validation:
  max_total_tokens: 10000
  min_confidence_score: 0.1
  max_conversation_history: 10
  required_sop_fields: ["sopId", "title", "summary", "format"]

# Debugging & Analytics  
debug:
  log_token_usage: true
  log_confidence_scores: true
  log_sop_selection_reasoning: true
  save_failed_queries: true